apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    type: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hello
  template:
    metadata:
      labels:
        component: hello
    spec:
        containers:
          - name: hello
            image: frannyoa/frankie_docker_1repo:latest
            ports:
              - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: hello
    labels:
      app: hello
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: hello
    tier: hello
    type: LoadBalancer
